// import './examples/1_basic-types'
// import './examples/2_symbol'
// import './examples/3_interface'
// import './examples/4_function'
// import './examples/5_generics'
// import './examples/6_classInEs6'
// import './examples/7_classInTs'
// import './examples/8_enum'
// import './examples/9_inferenceAndCompatibility'
// import './examples/10_advanced-types-1'
import './examples/11_advanced-types-2'
