// import './example/1_basic-types.ts'
// import './example/2_symbol'
// import './example/3_interface'
// import './example/4_function'
// import './example/5_generics'
// import './example/6_classInEs6'
// import './example/7_classInTs'
import './example/8_enum'
